name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image 
        run: |
            docker build -t saikrishna7783/bmskart-web:v1.0 .
        working-directory: ${{ github.workspace }}
  

      - name: Push Docker image 
        run: |
          docker push saikrishna7783/bmskart-web:v1.0
        working-directory: ${{ github.workspace }}